#!/bin/bash

curl -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
python /tmp/get-pip.py
rm -rf /tmp/get-pip.py

curl -o /tmp/get-pip.py https://bootstrap.pypa.io/3.3/get-pip.py
python3.6 /tmp/get-pip.py
rm -rf /tmp/get-pip.py

