#!/bin/bash
UID=$(id -u)
MYUSER="asevcenc"

rm -rf /tmp/gbbox_${UID}_* /tmp/gclient_env_${UID} /tmp/gclient_token_${UID} /tmp/x509up_u${UID}

alien-token-init ${MYUSER}

sed -i '/LD_LIBRARY_PATH/d' /tmp/gclient_env_${UID}
#source /tmp/gclient_env_$(id -u)

