#!/bin/bash
rm -rf /tmp/gbbox_`id -u`_*
rm -rf /tmp/gclient_env_`id -u`
rm -rf /tmp/gclient_token_`id -u`
rm -rf /tmp/x509up_u`id -u`

alien-token-init asevcenc

sed -i '/LD_LIBRARY_PATH/d' /tmp/gclient_env_$(id -u)
source /tmp/gclient_env_$(id -u)

