#!/bin/bash

TOKENINIT=$(which alien-token-init 2>/dev/null)

[[ -z "${TOKENINIT}" ]] && { echo "alien-token-init not found!!"; exit 1; }
[[ ! -w "${TOKENINIT}" ]] && { echo "alien-token-init found but NOT WRITABLE !!"; exit 1; }

INIT_LINE=$(grep "\$XRDGSIPROXY init" "${TOKENINIT}")

VALID_PREZENT=$(grep valid <<< "${INIT_LINE}" )

[[ -z "${VALID_PREZENT}" ]] && sed -i 's#$XRDGSIPROXY init#$XRDGSIPROXY init -valid 96:00#' "${TOKENINIT}"

