#!/bin/bash

ROOT_VER=$(root-config --version)
ROOT_VER_MAJOR=${ROOT_VER:0:1}
NCPU=$(root-config --ncpu)

if (( ROOT_VER_MAJOR == 5 )) ; then
  switch_aliphys r5
else
  switch_aliphys r6
fi

echo -e "ROOT version is : $ROOT_VER\n"
aliphys_status

CMAKECMD="cmake_alicephys"
PHYSICS_SRC="${ALICE}/physics-src"
PHYS_BUILDDIR="${ALICE}/BUILDPHYS"
PHYS_INSTALLDIR="${ALICE}/aliphysics"

mkdir -p ${PHYS_BUILDDIR}
cd ${PHYS_BUILDDIR}
rm -rf ${PHYS_BUILDDIR}/*

${CMAKECMD} ${PHYSICS_SRC}
make -j $NCPU

RV=$?
(("$RV" != "0")) && echo "Compilation not succesful; see ${PHYS_BUILDDIR}" && exit $RV

rm -rf ${PHYS_INSTALLDIR}/*
make install

RV=$?
(("$RV" != "0")) && echo "Instalation not succesful; see ${PHYS_BUILDDIR}" && exit $RV

rm -rf ${PHYS_BUILDDIR}/*

