#!/bin/bash

PHYSICS_SRC="$tools/alice/physics-src"
PHYS_BUILDDIR="$tools/alice/BUILDPHYS"
PHYS_INSTALLDIR="$tools/alice/physics"

cd ${PHYSICS_SRC}
#git apply ~/bin/CGAL-rootmap-dep.patch

cd ${PHYS_BUILDDIR}
rm -rf ${PHYS_BUILDDIR}/*

cmake_alicephys_r5 ${PHYSICS_SRC}
make -j8

rm -rf ${PHYS_INSTALLDIR}/*
make install


rm -rf ${PHYS_BUILDDIR}/*


