#!/bin/bash

CMAKECMD="cmake_alicephys_r6"

PHYSICS_SRC="$tools/alice/physics-src"
PHYS_BUILDDIR="$tools/alice/BUILDPHYS"
PHYS_INSTALLDIR="$tools/alice/physics-r6"

mkdir -p ${PHYS_BUILDDIR}
cd ${PHYSICS_SRC}
#git apply ~/bin/CGAL-rootmap-dep.patch

cd ${PHYS_BUILDDIR}
rm -rf ${PHYS_BUILDDIR}/*

${CMAKECMD} ${PHYSICS_SRC}
make -j`root-config --ncpu`

rm -rf ${PHYS_INSTALLDIR}/*
make install

rm -rf ${PHYS_BUILDDIR}/*


