#!/bin/bash

CMAKECMD="cmake_alice_r5"

ALIROOT_SRC="$tools/alice/v5-AN-latest-src"
ALIROOT_BUILDDIR="$tools/alice/BUILD"
ALIROOT_INSTALLDIR="$tools/alice/v5-AN"

mkdir -p ${ALIROOT_BUILDDIR}
cd ${ALIROOT_SRC}

cd ${ALIROOT_BUILDDIR}
rm -rf ${ALIROOT_BUILDDIR}/*

${CMAKECMD} ${ALIROOT_SRC}
make -j`root-config --ncpu`
RV=$?
(("$RV" != "0")) && echo "Compilation not succesful; see ${ALIROOT_BUILDDIR}" && exit $RV

rm -rf ${ALIROOT_INSTALLDIR}/*
make install
(("$RV" != "0")) && echo "Instalation not succesful; see ${ALIROOT_BUILDDIR}" && exit $RV

rm -rf ${ALIROOT_BUILDDIR}/*

