#!/usr/bin/env bash

NOW="$(date +%Y%m%d_%H%M%S)"
LOCK="/tmp/ans_gather_facts_host.lock"

exec {FD}>${LOCK} || exit 1
/usr/bin/flock -n ${FD} || exit 1
trap 'rm -f ${LOCK}' EXIT

TGT="${1}"
shift

ans_gather_facts ${@} ${TGT}

