#!/usr/bin/env bash

ARG="${1}"
shift

help () {
echo "${0} [ last_log | detail ]"
}

case "${ARG}" in
last_log)
    cat ${HOME}/ans_ping_all.log
    exit
    ;;
-h|--h|-help|--help|help)
    help
    exit
    ;;
detail)
    DETAIL="1"
    ;;
esac

source ~/py313/bin/activate

script -q /dev/null -c 'ansible all -m ping' > ${HOME}/ans_ping_all.log

[[ -z "${DETAIL}" ]] && { cat ${HOME}/ans_ping_all.log | sed -n '/PLAY RECAP/,$p'; } || { cat ${HOME}/ans_ping_all.log; }

