#!/usr/bin/env bash

OLD_PWD="$(pwd)"
cd "${HOME}/ansible/playbooks"

ARG1="${1}"
IS_HOST="$(ansible-inventory --list | grep ${ARG1})"

if [[ -n "${IS_HOST}" ]]; then
  TGT_SPEC="-e target=${ARG1}"
  shift
fi

ansible-playbook ${TGT_SPEC} "${@}"

cd "${OLD_PWD}"

