#!/usr/bin/env bash

[[ -z "${1}" ]] && { echo "${0} host_name task1_file task2_file .."; exit; }

HOST="${1}"
shift

cd "${HOME}/ansible/playbooks" || exit 1

NOW="$(date +%Y%m%d_%H%M%S)"
PBOOK_TMP="${HOST}_play.tmp${NOW}.yml"

cat > "${PBOOK_TMP}" <<EOF
---
- hosts: ${HOST}
  tasks:
EOF

declare -a ARGS
read -ra ARGS <<< "${@}"

declare -a task_list

for i in "${ARGS[@]}"; do
  if [[ -f "${i}" ]]; then
    task_list+=("${i}")
    echo "  - include_tasks: ${i}" >> "${PBOOK_TMP}"
  fi
done

for task in "${task_list[@]}"; do
  ARGS=( "${ARGS[@]/${task}/}" )
done

ansible-playbook ${ARGS[@]} ${PBOOK_TMP}
[[ -e "${PBOOK_TMP}" ]] && rm -f "${PBOOK_TMP}"

