#!/usr/bin/env bash

[[ -z "${ANSIBLE_HOME}" ]] && { echo "ANSIBLE_HOME not defined!!" ; exit 1; }
[[ -d "${ANSIBLE_HOME}" ]] || { echo "ANSIBLE_HOME defined but not present!!" ; exit 1; }

pushd "${ANSIBLE_HOME}/playbooks" &> /dev/null || { echo "Could not cd to ANSIBLE_HOME/playbooks"; exit 1; }
yml_list="$(ls -1 *.yml)"

INVENTORY_JSON="${ANSIBLE_HOME}/inventory.json"
ansible-inventory --list --export > "${INVENTORY_JSON}"

ansible_inventory_hosts=$(cat "${INVENTORY_JSON}" | jq -nr 'inputs[] | .hosts | values[]' | sort -u)
echo "${ansible_inventory_hosts}"

popd &> /dev/null

