#!/usr/bin/env bash

python3 -m pip install --upgrade $( [[ -z ${VIRTUAL_ENV} ]] && echo "--user" ) \
ansible ansible-core ansible-inventory ansible-lint ansible-compat ansible-rulebook ansible-runner

