#!/usr/bin/env bash

HOST="${1}"
shift
PBOOK="${1}"
shift

NOW="$(date +%Y%m%d_%H%M%S)"
PBOOK_TMP="$(basename ${PBOOK} .yml).tmp${NOW}.yml"
sed "/- hosts: /s/.*/- hosts: ${HOST}/" ${PBOOK} > ${PBOOK_TMP}
ansible-playbook "${@}" ${PBOOK_TMP}
[[ -e ${PBOOK_TMP} ]] && rm -rf ${PBOOK_TMP}

