#!/bin/bash

cd $ALICE/trunk-src
git pull
last_an_tag=`git tag -l "vAN-*" | tail -n 1`

cd $ALICE/vAN-latest-src
git pull
git checkout $last_an_tag

cd $ALICE/BUILD
rm -rf $ALICE/BUILD/*

cmake_alice $ALICE/vAN-latest-src
cmake_status=$?

[[ $cmake_status == 0 ]] && make -j8
compile_status=$?

if [[ $compile_status == 0 ]]
then
    rm -rf $ALICE/vAN-latest/*
    make install
    alice_build_sync
    echo "successful" > $ALICE/BUILD/status
fi

