#!/usr/bin/env python3

import sys
import os
import math

def convert_size(size_bytes):
   if size_bytes == 0: return "0B"
   size_name = ("B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "ZiB", "YiB")
   i = int(math.floor(math.log(size_bytes, 1024)))
   p = math.pow(1024, i)
   s = round(size_bytes / p, 2)
   return f'{s:.02f}{size_name[i]}'

sys.argv.pop(0)
if not sys.argv: sys.exit()

for size in sys.argv:
    if not size.isdecimal(): continue
    print(convert_size(int(size)))

