#!/usr/bin/env python3

import sys
import os
import requests
import hashlib

sys.argv.pop(0)  # remove program name
if not sys.argv:
    print(f'No arguments given!Usage: {sys.argv[0]} pasword_to_be_checked')
    sys.exit(1)

pw_nr = len(sys.argv)
pwned = 0
for p in sys.argv:
    pwd = p.strip().encode('utf-8')
    print(pwd)
    sha1 = hashlib.sha1()
    sha1.update(pwd)
    digest = sha1.hexdigest().upper()
    prefix = digest[0:5]
    suffix = digest[5:]
    query_str = f'https://api.pwnedpasswords.com/range/{prefix}'
    query = requests.get(query_str)
    if query.status_code == 200:
        hashes = query.text.splitlines()
        for h in hashes:
            if suffix in h:
                print('Pwned!!')
                pwned = pwned + 1
                break
print(f'Pwned {pwned} from {pw_nr}')
sys.exit(pwned)


