#!/bin/bash

DEFAULT_BUILD_TYPE="RelWithDebInfo"

BUILDTYPE==${2:-$DEFAULT_BUILD_TYPE}

#PEDANTIC="-Wall -Wextra"
PEDANTIC=""

CXXFLAGS="${PEDANTIC} -march=native"

# Build with C++11?
root_cxx11=`root-config --has-cxx11`
[[ "$root_cxx11" == "yes" ]] && CXXFLAGS="${CXXFLAGS} -std=c++11"

# AVX
avx_enable=`grep avx /proc/cpuinfo &> /dev/null && echo yes`
[[ ${avx_enable} == "yes" ]] && CXXFLAGS="${CXXFLAGS} -mavx"

cmake \
-DCMAKE_C_COMPILER=`root-config --cc` -DCMAKE_CXX_COMPILER=`root-config --cxx` -DCMAKE_Fortran_COMPILER=`root-config --f77` \
-DCMAKE_INSTALL_PREFIX=$tools/alice/v5-AN \
-DCMAKE_CXX_FLAGS=${CXXFLAGS} \
-DCMAKE_BUILD_TYPE=$BUILDTYPE \
-DROOTSYS=${tools}/root/v5-34_reldbg \
-DALIEN=${ALIEN_ROOT} \
-DFASTJET=${FASTJET_ROOT} \
-DTARGET_ARCHITECTURE="auto" \
-DVC_IMPL="auto" \
$1 | tee cmake_out.txt



##-DFASTJET=$FASTJET_ROOT \
##-DApMon=${tools}/heplibs/ApMon \
###-DGEANT3_SYSTEM_DIR=${GEANT3DIR} \


###-DZEROMQ_INCLUDE_DIR="/usr/include" \

#-DFACTEXTRACTOR_JAR=$ALICE/aliroot-src/RuleChecker/FactExtractor.jar \
#-DSMELLDETECTOR_JAR=$ALICE/aliroot-src/RuleChecker/SmellDetector.jar \
#-DRULECHECKER_JAR=$ALICE/aliroot-src/RuleChecker/NewRuleChecker.jar \
#-DRULECHECKER_RULES=$ALICE/aliroot-src/RuleChecker/CodingConventions.xml \
#-DRULECHECKER_SRCML=$tools/heplibs/srcML \

#-DGEANT3_SYSTEM_DIR="${ALICE}/geant3" \
#-DGEANT3_INCLUDE_DIR="${ALICE}/geant3/include" \
#-DGEANT3_LIBRARY_DIR="${ALICE}/geant3/lib64" \
#-DGEANT3_LIB="${ALICE}/geant3/lib64/libgeant321.so" \
