#!/bin/bash

DEFAULT_BUILD_TYPE="RELWITHDEBINFO"

BUILDTYPE=${2:-$DEFAULT_BUILD_TYPE}

#PEDANTIC="-Wall -Wextra"
PEDANTIC=""

ROOT_DIR=$(root-config --prefix)

# AVX
FQDN=`hostname -f`
if [[ "$FQDN" != "issaf.spacescience.ro"  ]] ; then
  GCCARCH="-march=native -mtune=native"
  avx_enable=`grep avx /proc/cpuinfo &> /dev/null && echo yes`
  [[ ${avx_enable} == "yes" ]] && AVX="-mavx"
else
  ISSAF_OPT="-DVC_IMPL="SSE" -D_last_target_arch="generic" -DTARGET_ARCHITECTURE="generic" "
  GCCARCH="-march=core2"
fi

CXXFLAGS="${PEDANTIC} ${GCCARCH} ${AVX}"

cmake \
-DCMAKE_INSTALL_PREFIX=$tools/alice/aliroot \
-DCMAKE_BUILD_TYPE=$BUILDTYPE \
-DCMAKE_CXX_FLAGS=${CXXFLAGS} \
-DROOTSYS=${ROOT_DIR} \
-DALIEN=${ALIEN_ROOT} \
-DFASTJET=${FASTJET_ROOT} \
-DOCDB_INSTALL=PLACEHOLDER \
$1 | tee cmake_out.txt

