#!/bin/bash

cmake \
-DCMAKE_INSTALL_PREFIX="${tools}/heplibs/geant4_vmc" \
-DGEANT4_CONFIG_EXECUTABLE="$tools/geant4/bin/geant4-config" \
-DGeant4VMC_INSTALL_EXAMPLES="0" \
-DGeant4VMC_USE_GEANT4_G3TOG4="1" \
-DGeant4VMC_BUILD_EXAMPLES="0" \
$1

