#!/bin/bash

DEFAULT_BUILD_TYPE="RELWITHDEBINFO"

BUILDTYPE=${2:-$DEFAULT_BUILD_TYPE}

#PEDANTIC="-Wall -Wextra"
PEDANTIC=""

# AVX
FQDN=`hostname -f`
if [[ "$FQDN" != "issaf.spacescience.ro"  ]] ; then
  GCCARCH="-march=native -mtune=native"
  avx_enable=`grep avx /proc/cpuinfo &> /dev/null && echo yes`
  [[ ${avx_enable} == "yes" ]] && AVX="-mavx"
else
  ISSAF_OPT="-DVC_IMPL="SSE" -D_last_target_arch="generic" -DTARGET_ARCHITECTURE="generic" "
  GCCARCH="-march=core2"
fi

CXXFLAGS="${PEDANTIC} ${GCCARCH} ${AVX}"

[[ -z $CGAL_LIB ]] && CGAL_LIB="/usr/lib64/"

ROOT_DIR=$(root-config --prefix)

cmake \
-DCMAKE_INSTALL_PREFIX=$ALICE/aliphysics \
-DCMAKE_BUILD_TYPE=${BUILDTYPE} ${ISSAF_OPT} -DCMAKE_CXX_FLAGS=${CXXFLAGS} \
-DALIEN="$ALIEN_ROOT" \
-DFASTJET="$ALICE/fastjet" \
-DROOTSYS=${ROOT_DIR} \
-DCGAL_LIB="$CGAL_LIB" \
-DALIROOT="$ALICE/aliroot" \
$1 | tee cmake_out.txt


