#!/bin/bash

echo "This should be run in BUILD directory;"
echo "the argument should be the path to the source"

g4install=$tools/geant4
g4source=$1

g4_version=`grep geant4 $1/source/GNUmakefile | awk '{print $6}'`
echo $g4_version


cmake \
-DCMAKE_INSTALL_PREFIX=$g4install \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DGEANT4_BUILD_MULTITHREADED=1 \
-DGEANT4_INSTALL_DATA=0 \
-DGEANT4_USE_GDML=1 \
-DGEANT4_USE_G3TOG4=1 \
-DGEANT4_USE_OPENGL=1 \
-DGEANT4_USE_OPENGL_X11=1 \
-DGEANT4_USE_RAYTRACER_X11=1 \
-DGEANT4_USE_SYSTEM_EXPAT=1 \
-DGEANT4_USE_XM=1 \
-DGEANT4_USE_QT=1 \
-DGEANT4_USE_SYSTEM_ZLIB="0" \
-DGEANT4_BUILD_STORE_TRAJECTORY=1 \
-DGEANT4_BUILD_VERBOSE_CODE=1 \
-DGEANT4_INSTALL_DATADIR="/home/physics-tools/geant4-data" \
-DGEANT4_USE_SYSTEM_CLHEP=1 \
-DCLHEP_ROOT_DIR="/home/physics-tools/heplibs/clhep" \
-DCLHEP_CONFIG_EXECUTABLE="/home/physics-tools/heplibs/clhep/bin/clhep-config" \
-DCLHEP_LIBRARY="/home/physics-tools/heplibs/clhep/lib/libCLHEP.so" \
-DCLHEP_INCLUDE_DIR="/home/physics-tools/heplibs/clhep/include" \
$g4source

#-DHEPMC_INCLUDE_DIR=/home.hdd/physics-tools/HepMC/include \
#-DHEPMC_LIBRARIES=/home.hdd/physics-tools/HepMC/lib/libHepMC.so \
# -Dgdml_DIR=$tools/gdml/schema \

