#!/bin/bash

# http://xrootd.org/doc/dev410/cms_config.htm#_Toc8247264
# The specified program must write 5 white-space separated numbers to standard out.
# The last number must be terminated by a new-line character (“\n”).
# Each number must be normalized to 100, with 0 indicating no load and 100 indicating saturation. The numbers are in the order:
# 1.      system load
# 2.      cpu utilization
# 3.      memory utilization
# 4.      paging load, and
# 5.      network utilization.

NCPU=$(awk '/processor/ {nr++} END{print nr}' /proc/cpuinfo)

LOAD5=$(awk '{print int($2*100/'${NCPU}')}' /proc/loadavg)
[[ "${LOAD5}" -gt "100" ]] && LOAD5="100"

# procs -----------------------memory---------------------- ---swap-- -----io---- -system-- --------cpu--------
#  r  b         swpd         free         buff        cache   si   so    bi    bo   in   cs  us  sy  id  wa  st
CPU_UTIL_INFO=$(vmstat 1 2 | tail -n1)

CPU=$(echo "${CPU_UTIL_INFO}" | awk '{print $(NF-3) + $(NF-4)  }') #'
#CPU_WA=$(echo "${CPU_UTIL_INFO}" | awk '{print $(NF-1)  }') #'

MEM=$(awk '/MemTotal/{MEM_TOT=$(NF-1)}/MemFree/{MEM_FREE=$(NF-1)}END{print int((MEM_TOT-MEM_FREE)/MEM_TOT*100)}' /proc/meminfo)

# should be replaced by IOwait/NCPU ?
PGIO=0

NET_LOAD="0"
IFACE_DIR="/sys/class/net"
for iface in ${IFACE_DIR}/*; do
  IFACE_NAME=${iface##*/}
  [ "${IFACE_NAME}" = "lo" ] && continue
  OPERSTATE=$(< ${iface}/operstate)
  [ "$OPERSTATE" != "up" ] && continue
  SPEED=$(< ${iface}/speed)
  if [ ! $? -eq 0 ]; then
    SPEED=1000
  elif [ ! ${SPEED} -gt 0 ]; then
    SPEED=1000
  fi
  SPEED_BYTES=$(awk "BEGIN{print int(${SPEED} * 1000000/8)}")

  RX1=$(< ${iface}/statistics/rx_bytes)
  TX1=$(< ${iface}/statistics/tx_bytes)

  sleep 1
  RX2=$(< ${iface}/statistics/rx_bytes)
  TX2=$(< ${iface}/statistics/tx_bytes)

  RX_DIFF=$((RX2-RX1))
  TX_DIFF=$((TX2-TX1))

  RX_PERC=$(awk "BEGIN{print int(${RX_DIFF}*100/${SPEED_BYTES})}")
  TX_PERC=$(awk "BEGIN{print int(${TX_DIFF}*100/${SPEED_BYTES})}")

  if [ ${RX_PERC} -gt ${NET_LOAD} ]; then
    NET_LOAD=${RX_PERC}
  fi
  if [ ${TX_PERC} -gt ${NET_LOAD} ]; then
    NET_LOAD=${TX_PERC}
  fi
done

echo -ne "${LOAD5} ${CPU} ${MEM} ${PGIO} ${NET_LOAD}\n"

