#!/bin/bash

PREFIX="${tools}/root/v5-34-08"

./configure \
--prefix=$PREFIX --etcdir=$PREFIX/etc --incdir=$PREFIX/include --libdir=$PREFIX/lib --datadir=$PREFIX/share --docdir=$PREFIX/doc --build=debug \
--with-pythia6-uscore=SINGLE --disable-globus --disable-gfal \
--enable-soversion --enable-table --enable-unuran --enable-gdml --enable-roofit --enable-minuit2 --enable-gsl-shared --enable-afdsmgrd \
--enable-builtin-freetype --enable-builtin-pcre --enable-builtin-ftgl --enable-builtin-glew --enable-builtin-zlib --enable-builtin-lzma \
--with-qt-incdir=/usr/include --with-qt-libdir=/usr/lib64 \
--enable-pythia8 --with-pythia8-incdir="${tools}/heplibs/pythia8/include" --with-pythia8-libdir="${tools}/heplibs/pythia8/lib" \
--with-alien-incdir=${GSHELL_ROOT}/include --with-alien-libdir=${GSHELL_ROOT}/lib \
--with-xrootd-incdir=${GSHELL_ROOT}/include/xrootd --with-xrootd-libdir=${GSHELL_ROOT}/lib \
--with-monalisa-incdir="${tools}/heplibs/ApMon/include" --with-monalisa-libdir="${tools}/heplibs/ApMon/lib"


##--enable-mysql --enable-builtin-afterimage ---> enabled by default

# --with-xml-incdir=/opt/aliroot/install/alien/include/libxml2
# --with-xml-libdir=/opt/aliroot/install/alien/lib


# --with-ssl-shared=yes
# --with-ssl-incdir=/opt/aliroot/install/alien/include
# --with-ssl-libdir=/opt/aliroot/install/alien/lib

