#!/usr/bin/env python3

import os
import glob
import re
from datetime import datetime

def extract_date_from_name(name):
    tokens = name.split('-')
    for token in tokens:
        if re.fullmatch(r"\d{8}", token):
            try:
                return datetime.strptime(token, "%Y%m%d")
            except ValueError:
                continue
    for token in tokens:
        if re.fullmatch(r"20\d{2}", token):
            try:
                return datetime.strptime(token, "%Y")
            except ValueError:
                continue
    return datetime.min


def cvmfs_list_o2phys():
    pattern = "/cvmfs/alice.cern.ch/*/Modules/modulefiles/O2Physics"
    pkg_list = []

    for path in glob.glob(pattern):
        if os.path.isdir(path):
            try:
                #entries = os.listdir(path)
                #entries = sorted(, key=extract_date_from_name, reverse=False)
                pkg_list.extend(os.listdir(path))
            except OSError as e:
                print(f"Error listing directory {path}: {e}")

    pkg_list = sorted(pkg_list, key = extract_date_from_name, reverse = False)
    print("\n".join(pkg_list))


cvmfs_list_o2phys()
