#!/usr/bin/env bash

pushd ${HOME}/DIRACOS || { echo "Could not cd to ${HOME}/DIRACOS"; exit 1; }

curl -LO https://github.com/DIRACGrid/DIRACOS2/releases/latest/download/DIRACOS-Linux-$(uname -m).sh
bash DIRACOS-Linux-$(uname -m).sh -f -p ${HOME}/DIRACOS -u

rm -rf DIRACOS-Linux-$(uname -m).sh
popd

