#!/bin/bash

inputf=$1
file_arg=$2

now_str () { /usr/bin/date +%Y%m%d_%H%M%S; }

USRDIR="/alice/cern.ch/user"

FILE_USER="AnalysisResults.root"
FILE_DATA_AOD="AliAOD.root"
FILE_DATA_ESD="AliESD.root"
ZIPFILE="root_archive.zip"

FILES_LIST="file_list_$(now_str)"

[[ -z "${file_arg}" ]] && FILE=${FILE_DATA_AOD}
[[ "${file_arg}" =~ ^[A,a][O,o][D,d]$ ]] && FILE=${FILE_DATA_AOD}
[[ "${file_arg}" =~ ^[E,e][S,s][D,d]$ ]] && FILE=${FILE_DATA_ESD}
[[ "${file_arg}" =~ ^[Z,z][I,i][P,p]$ ]] && FILE=${ZIPFILE}
[[ "${file_arg}" =~ ^[U,u][S,s][E,e][R,r]$ ]] && FILE=${FILE_USER}

while read -r line; do
    [[ "${line}" =~ ^#.*$ ]] && continue
    [[ -z "${line}" ]] && continue

    extension=$( [[ "${line}" == *.* ]] && echo "${line##*.}" || echo '' )
    if [[ -n "${extension}" ]]; then
        echo "Extension found, the input is a list of files. Swithing to download_alien_files";
        exec download_alien_files "${inputf}"
    fi

    alien_find -s ${line} ${FILE} | head -n -2 >> ${FILES_LIST}

done < "${inputf}"

## starting the download of gathered files
exec download_alien_files ${FILES_LIST}

