#!/bin/bash

inputf=$1

MYHOME=$( [[ -e /tmp/gclient_env_${UID} ]] || { >&2 echo "Create AliEn token first"; exit;}; source /tmp/gclient_env_${UID} && cat ${GBBOX_ENVFILE}; )

CURDIR=$(pwd)

while read -r line; do
    [[ "${line}" =~ ^#.*$ ]] && continue
    [[ -z "${line}" ]] && continue
    filepath="${line#${MYHOME}}"
    path=$(/usr/bin/dirname ${filepath})
    filename=$(/usr/bin/basename ${filepath})
    local_file_path=${CURDIR}/${path}/${filename}

    if [[ ( -e ${local_file_path} ) && ( -f ${local_file_path} ) ]] ; then
      fsize=$(/usr/bin/stat -c %s ${local_file_path})
      alien_size=$(alien_ls -l ${line} | awk '{print $4}')

      if [[ ( "${fsize}" -eq "0" ) || ( ! "${fsize}" -eq "${alien_size}" )  ]] ; then
        echo -ne "File is 0 size or different size from alien. Removing ... "
        rm -rf ${local_file_path}
        echo "Done!"
      else
        echo "File exists in ${local_file_path}" && continue
      fi
    fi

    mkdir -p ${CURDIR}/${path}
    alien_cp -v alien://${line} ${local_file_path}

done < "${inputf}"

