#!/bin/bash

inputf=$1

now_str () { /usr/bin/date +%Y%m%d_%H%M%S; }

ALIEN_DOWNLOAD_THREADS=${ALIEN_DOWNLOAD_THREADS:=8}

LOGFILE="${inputf}_$(now_str).log"

MYHOME=$( [[ -e /tmp/gclient_env_${UID} ]] || { >&2 echo "Create AliEn token first"; exit;}; source /tmp/gclient_env_${UID} && cat ${GBBOX_ENVFILE}; )
CURDIR=$(pwd)

USRDIR="/alice/cern.ch/user"

download_file () { {
while read -r line; do
    [[ "${line}" =~ ^#.*$ ]] && continue
    [[ -z "${line}" ]] && continue

    local extension=$( [[ "${line}" = *.* ]] && echo "${line##*.}" || echo '' )
    [[ -z "${extension}" ]] && { echo "Extension not found, not a list of files. Use alien_find to create a list of files"; continue; }

    if [[ "${line}" =~ "${USRDIR}" ]] ; then
        local filepath=$(echo "${line}" | awk -F/ '{ for (i=1; i<=6; i++) { gsub($i,"",$0);}; gsub(/^\/+/,"",$0);print $0;}') #'
    else
        local filepath=$(echo "${line}" | awk '{ gsub (/^\/*(alice)*\/*/,"",$0); print $0;}') #'
    fi

    local path=$(/usr/bin/dirname ${filepath})
    local filename=$(/usr/bin/basename ${filepath})
    local local_path=${CURDIR}/${path}
    local local_file=${local_path}/${filename}

    if [[ ( -e ${local_file} ) && ( -f ${local_file} ) ]] ; then
      local fsize=$(/usr/bin/stat -c %s ${local_file})
      local alien_size=$(alien_ls -l ${line} | awk '{print $4}')

      if [[ ( "${fsize}" -eq "0" ) || ( ! "${fsize}" -eq "${alien_size}" )  ]] ; then
        echo -ne "File is 0 size or different size from alien. Removing ... "
        rm -rf ${local_file}
        echo "Done!"
      else
        echo "File exists in ${local_path}" && continue
      fi
    fi

    mkdir -p ${local_path}
    alien_cp alien://${line} ${local_path}/

done < "${1}"
} &> ${1}.log }

/usr/bin/split -a 3 -e -d -n l/${ALIEN_DOWNLOAD_THREADS} ${inputf} "${inputf}_"

for f in ${inputf}_* ; do
    download_file ${inputf} &
done
wait
rm -rf ${inputf}_*
