#!/bin/bash

du -xb --max-depth=1 "$@"  | sort -nr | awk '{ kbyte=int($1/1024); if (kbyte==0) {print $1, $2; next;}; mbyte=int($1/(1024*1024)); if (mbyte==0) {print kbyte "KB",$2; next;}; gbyte=int($1/(1024*1024*1024)); if (gbyte==0) {print mbyte "MB",$2; next;}; print gbyte "GB",$2; }'   #'

