#!/bin/bash
##--display=DISPLAY
exec nohup firefox --new-instance --profile $HOME/.mozilla/firefox/PAOSHIFT \
--new-window http://10.10.10.180:10145/ \
--new-window http://10.10.10.180:10245/ \
--new-window http://10.10.10.180:10345/ \
--new-window http://10.10.10.180:10445/ \
"$@" </dev/null >${HOME}/firefox-pao-bg.log 2>&1 &
