#!/bin/bash

FULLCMD="${0}"
CMD="$(basename ${FULLCMD})"

METHOD="merge"
[[ "${CMD}" =~ pull ]] && METHOD="pull"

REPO_NAME=$(basename $(git remote get-url origin) .git)
HEAD_NAME_ORIGIN=$(git remote show origin | awk -F": " '/HEAD branch/ {print $2}')
HEAD_NAME_UPSTREAM=$(git remote show upstream | awk -F": " '/HEAD branch/ {print $2}')

git checkout ${HEAD_NAME_ORIGIN}
git fetch -t --all
git pull --rebase

if [[ "${METHOD}" == "pull" ]]; then
  git pull --rebase upstream ${HEAD_NAME_UPSTREAM}
else
  git merge --ff-only upstream/${HEAD_NAME_UPSTREAM}
fi

echo "doing push --all ..."
git push --all
echo "done"

