#!/usr/bin/env bash

H="${1}"
shift
[[ -z "${H}" ]] && { echo "Host argument is not specified"; exit 1; }

ipmimonitoring -u ADMIN -p $(< ~/ipmipass) ${@} \
--ignore-unrecognized-events \
--ignore-not-available-sensors \
--bridge-sensors \
--shared-sensors \
--interpret-oem-data \
-h ${H}
