#!/bin/bash

echo "Usage: `basename $0` local_port remote_port"

CMD="ssh -t -f -N -L"
LOCAL_PORT=5900
REMOTE_PORT=5900
REMOTE_SERVER="iss"

[[ -n "$1" ]] && LOCAL_PORT=$1
[[ -n "$2" ]] && REMOTE_PORT=$2

EXISTENT=`ps -C ssh -o pid=,args= | grep "$CMD$LOCAL_PORT"`

if [ -n "$EXISTENT" ]
then
  PREV_PID=`echo $EXISTENT | awk '{print $1}'`
  kill -9 $PREV_PID
fi

COMMAND=$CMD" "$LOCAL_PORT":localhost:"$REMOTE_PORT" iss"

eval $COMMAND
