#!/bin/bash

# Default check for user{cert,key}.pem ;
if [ ! -f "$HOME/.globus/userkey.pem" -o ! -f "$HOME/.globus/usercert.pem" ]; then
    echo "Your Grid user certificate should be stored in $HOME/.globus/{usercert,userkey}.pem"
    exit 1
fi

# if not defined use default .j/config
JALIEN_CONF_DIR=${JALIEN_CONF_DIR:-${HOME}/.j/config}
if [[ ! -d "${JALIEN_CONF_DIR}" ]]; then # ups, setup was not run
    echo "could not find ${JALIEN_CONF_DIR}; you should run:"
    echo "${0} setup"
    exit 1
fi

# check if command arguments have jar files and build a list of them as classpath definition
ARGLIST="$@"
for jar in ${ARGLIST}; do
    if [[ ${jar} =~ .*\.jar ]]; then
        JARFILE="${BASH_REMATCH[0]}"
        [[ -z "${JARLIST}" ]] && JARLIST="${JARFILE}" || JARLIST="${JARLIST}:${JARFILE}";
        JARDIR="$(dirname ${JARFILE})"
        [[ ! ${JARLIST} =~ :${JARDIR} ]] && JARLIST="${JARLIST}:${JARDIR}" # use ":" when checking if path already added otherwise will match all paths of files

        ARGLIST=${ARGLIST//${JARFILE}/} # remove the found jar files from the argument list that will be than passed to java cmd
    fi
done
export CLASSPATH="${JARLIST}"

# if the command line have no jar files then find JALIEN_HOME and create CLASSPATH with all jars found there
if [[ -z "${JARLIST}" ]]; then
  if [[ -z "${JALIEN_HOME}" ]]; then
    ## find the location of jalien script
    SOURCE="${BASH_SOURCE[0]}"
    while [ -h "${SOURCE}" ]; do ## resolve $SOURCE until the file is no longer a symlink
      JALIEN_HOME="$( cd -P "$(dirname "${SOURCE}" )" && pwd )" ##"
      SOURCE="$(readlink "${SOURCE}")" ##"
      [[ "${SOURCE}" != /* ]] && SOURCE="${JALIEN_HOME}/${SOURCE}" ## if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    JALIEN_HOME="$(cd -P "$( dirname "${SOURCE}" )" && pwd)" ##"
    export JALIEN_HOME
  fi

  JAR_LIST_MAIN="";
  for mainjar in ${JALIEN_HOME}/*.jar; do JAR_LIST_MAIN="${JAR_LIST_MAIN}${mainjar}:" ; done;
  JAR_LIST_MAIN=$( echo "${JAR_LIST_MAIN}" | sed 's/.$//')

  JAR_LIST_LIB="";
  for libjar in ${JALIEN_HOME}/lib/*.jar; do JAR_LIST_LIB="${JAR_LIST_LIB}${libjar}:" ; done;
  JAR_LIST_LIB=$( echo "${JAR_LIST_LIB}" | sed 's/.$//')

  export CLASSPATH="${JAR_LIST_MAIN}:${JAR_LIST_LIB}"
fi

#JALIEN_OPTS_DEFAULT="-server -Xms64m -Xmx256m -XX:+UseG1GC -XX:+DisableExplicitGC -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:MaxTrivialSize=1K \
#-XX:CompileThreshold=20000 -Duserid=$(id -u) -Dcom.sun.jndi.ldap.connect.pool=false"

JALIEN_OPTS_DEFAULT="-client -Xms16M -Xmx64M -Duserid=$(id -u)"

#JAVA_VERSION=$(java -version 2>&1 | sed -e 's/.*version "\([[:digit:]]*\)\(.*\)/\1/; 1q') #'
##JAVA_OPTS="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"

[[ -z "${FOUND_TMP}" ]] && FOUND_TMP="${TMPDIR}"
[[ -z "${FOUND_TMP}" ]] && FOUND_TMP="${TMP}"
[[ -z "${FOUND_TMP}" ]] && FOUND_TMP="${TEMP}"
[[ -z "${FOUND_TMP}" ]] && FOUND_TMP="/tmp"

JALIEN_OPTS_DEFAULT="${JALIEN_OPTS_DEFAULT} -Djava.io.tmpdir=${FOUND_TMP}"

ARG1="${1}"
if [ "${ARG1}" == "setup" ]; then
    #Copy the default logging and config files to user controllable versions - if present, keep the existing and copy the new ones with date postfix
    JCONFDIR="${JALIEN_HOME}/config/"
    USERCONFDIR="${HOME}/.j/config/"

    mkdir -p "${USERCONFDIR}"

    cat << EOF > ${USERCONFDIR}/config.properties
ldap_server = alice-ldap.cern.ch:8389
ldap_root = o=alice,dc=cern,dc=ch
alien.users.basehomedir = /alice/cern.ch/user/
alice_close_site = CERN
#xrootd.location=/home/mmmartin/alien/api/
apiService = alice-jcentral.cern.ch:8098
#siteProxyService = pcep.cern.ch:5284
#service.jks.location =
#user.jks.location =
jalien.config.hasDBBackend=false
EOF

    cat << EOF > ${USERCONFDIR}/logging.properties
handlers = alien.log.SevereFileHandler alien.log.WarningFileHandler alien.log.ConfigFileHandler alien.log.InfoFileHandler alien.log.FineFileHandler alien.log.FinerFileHandler alien.log.FinestFileHandler
#alien.site.CustomHandler

java.util.logging.SimpleFormatter.format = %1$tc %2$s %4$s: [ %5$s ] %6 %n %7 %n

alien.log.SevereFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.SevereFileHandler.limit = 1000000
alien.log.SevereFileHandler.count = 4
alien.log.SevereFileHandler.append = true
alien.log.SevereFileHandler.pattern = ${HOME}/alien-severe%g.log

alien.log.WarningFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.WarningFileHandler.limit = 1000000
alien.log.WarningFileHandler.count = 4
alien.log.WarningFileHandler.append = true
alien.log.WarningFileHandler.pattern = ${HOME}/alien-warning%g.log

alien.log.ConfigFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.ConfigFileHandler.limit = 1000000
alien.log.ConfigFileHandler.count = 4
alien.log.ConfigFileHandler.append = true
alien.log.ConfigFileHandler.pattern = ${HOME}/alien-config%g.log

alien.log.InfoFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.InfoFileHandler.limit = 1000000
alien.log.InfoFileHandler.count = 4
alien.log.InfoFileHandler.append = true
alien.log.InfoFileHandler.pattern = ${HOME}/alien-info%g.log

alien.log.FineFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.FineFileHandler.limit = 1000000
alien.log.FineFileHandler.count = 4
alien.log.FineFileHandler.append = true
alien.log.FineFileHandler.pattern = ${HOME}/alien-fine%g.log

alien.log.FinerFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.FinerFileHandler.limit = 1000000
alien.log.FinerFileHandler.count = 4
alien.log.FinerFileHandler.append = true
alien.log.FinerFileHandler.pattern = ${HOME}/alien-finer%g.log

alien.log.FinestFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.FinestFileHandler.limit = 1000000
alien.log.FinestFileHandler.count = 4
alien.log.FinestFileHandler.append = true
alien.log.FinestFileHandler.pattern = ${HOME}/alien-finest%g.log

.level = WARNING
lia.level = WARNING
lazyj.level = WARNING
apmon.level = WARNING
alien.level = FINEST
alien.monitoring.Monitor.level = WARNING

# tell LazyJ to use the same logging facilities
use_java_logger=true
EOF

    #mkdir -p ${HOME}/.j/trusts
    #wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Certification%20Authority.crt" -O ${HOME}/.j/trusts/CERN_CA.der
    #wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Root%20Certification%20Authority%202.crt" -O ${HOME}/.j/trusts/CERN_ROOT_CA2.der
    #wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Grid%20Certification%20Authority.crt" -O ${HOME}/.j/trusts/CERN_Grid_CA.der
    exit 0 # we done our job, let's exit

elif [ "${ARG1}" == "cleanup" ]; then
    # clean up the remaining JBox process
    JBOX_PID="$(ps -u $(id -u) -f | awk '/[a]lien.JBox/ {print $2}')"
    [[ -n "${JBOX_PID}" ]] && kill "${JBOX_PID}"
    exit 0 # we done our job, let's exit
elif [ "${ARG1}" == "login" ]; then
    RUNSH_OPTS="-DAliEnConfig=${JALIEN_CONF_DIR} alien.JBox"
    shift
elif [ "${ARG1}" == "run" ]; then
    # allows running custom commands from cli
    RUNSH_OPTS="-DAliEnConfig=${JALIEN_CONF_DIR}"
    shift
else
    RUNSH_OPTS="-DAliEnConfig=${JALIEN_CONF_DIR} alien.JSh"
fi

ARGLIST="$@"

# prepend any JALIEN_OPTS additional options to java command to be run
[[ -n "${JALIEN_OPTS}" ]] && RUNSH_OPTS="${JALIEN_OPTS} ${RUNSH_OPTS}"
exec java ${JALIEN_OPTS_DEFAULT} ${ARGLIST} ${RUNSH_OPTS}

