#!/usr/bin/env bash

# Default check for user{cert,key}.pem ;
if [ ! -f "$HOME/.globus/userkey.pem" -o ! -f "$HOME/.globus/usercert.pem" ]; then
    echo "Your Grid user certificate should be stored in $HOME/.globus/{usercert,userkey}.pem"
    exit 1
fi

# if not defined use default .alien/config
JALIEN_CONF_DIR=${JALIEN_CONF_DIR:-${HOME}/.alien/config}
[[ ! -d "${JALIEN_CONF_DIR}" ]] && mkdir -p "${JALIEN_CONF_DIR}"
JUSRDIR="$(dirname ${JALIEN_CONF_DIR})"

export TMPDIR="${TMPDIR:-/tmp}"

# export JALIEN_GC=" -XX:+UseG1GC -XX:+DisableExplicitGC -XX:MaxTrivialSize=1K"
JDK_JAVA_OPTIONS="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"
JALIEN_OPTS_DEFAULT="${JDK_JAVA_OPTIONS} -client -Xms16M -Xmx64M -Dcom.sun.jndi.ldap.connect.pool=false -Duserid=$(id -u) -Djava.io.tmpdir=${TMPDIR} -DAliEnConfig=${JALIEN_CONF_DIR}"

# prepend any JALIEN_OPTS additional options to java command to be run
RUNSH_OPTS="${JALIEN_OPTS} ${RUNSH_OPTS}"

ARG1="${1}"
shift

# check if command arguments have jar files and build a list of them as classpath definition
ARGLIST="${@}"
for jar in ${ARGLIST}; do
    if [[ ${jar} =~ .*\.jar ]]; then
        JARFILE="${BASH_REMATCH[0]}"
        [[ -z "${JARLIST}" ]] && JARLIST="${JARFILE}" || JARLIST="${JARLIST}:${JARFILE}";
        JARDIR="$(dirname ${JARFILE})"
        [[ ! ${JARLIST} =~ :${JARDIR} ]] && JARLIST="${JARLIST}:${JARDIR}" # use ":" when checking if path already added otherwise will match all paths of files

        ARGLIST=${ARGLIST//${JARFILE}/} # remove the found jar files from the argument list that will be then passed to java cmd
    fi
done
export CLASSPATH="${JARLIST}"

# if the command line have no jar files then find JALIEN_HOME and create CLASSPATH with all jars found there
if [[ -z "${JARLIST}" ]]; then
  if [[ -z "${JALIEN_HOME}" ]]; then
    ## find the location of jalien script
    SOURCE="${BASH_SOURCE[0]}"
    while [ -h "${SOURCE}" ]; do ## resolve $SOURCE until the file is no longer a symlink
      JALIEN_HOME="$( cd -P "$(dirname "${SOURCE}" )" && pwd )" ##"
      SOURCE="$(readlink "${SOURCE}")" ##"
      [[ "${SOURCE}" != /* ]] && SOURCE="${JALIEN_HOME}/${SOURCE}" ## if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    JALIEN_HOME="$(cd -P "$( dirname "${SOURCE}" )" && pwd)" ##"
    export JALIEN_HOME
  fi

  JAR_LIST_MAIN="";
  for mainjar in ${JALIEN_HOME}/*.jar; do JAR_LIST_MAIN="${JAR_LIST_MAIN}${mainjar}:" ; done;
  JAR_LIST_MAIN=$( echo "${JAR_LIST_MAIN}" | sed 's/.$//')

  JAR_LIST_LIB="";
  for libjar in ${JALIEN_HOME}/lib/*.jar; do JAR_LIST_LIB="${JAR_LIST_LIB}${libjar}:" ; done;
  JAR_LIST_LIB=$( echo "${JAR_LIST_LIB}" | sed 's/.$//')

  export CLASSPATH="${JAR_LIST_MAIN}:${JAR_LIST_LIB}"
fi

# clean up the remaining JBox process
jbox_stop () {
    pkill -u $(id -u) -e -f [a]lien.JBox
    sleep 1
    pgrep -u $(id -u) -a -f [a]lien.JBox > /dev/null || pkill -9 -u $(id -u) -e -f [a]lien.JBox
    }

jbox_start () {
    pgrep -u $(id -u) -a -f [a]lien.JBox > /dev/null && return 0;
    PIPE="${TMPDIR}/jbox_input_$(id -u).pipe"
    [[ -e "${PIPE}" ]] && rm -rf "${PIPE}"
    mkfifo ${PIPE}
    read -t 30 -s -p "SSL key password: " PASS
    [[ -z "${PASS}" ]] && { echo "SSL key password was not provided!"; return 1; }
    nohup java ${JALIEN_OPTS_DEFAULT} ${RUNSH_OPTS} alien.JBox &>${HOME}/jbox.out <${PIPE} &
    sleep 0.5
    echo -e "${PASS}\n" > ${PIPE}
    echo -ne "\nJBOX starting"
    times=7; i=0; while((i++ < times)); do echo -n "."; sleep 1; done;
    echo " done"
    cat ${HOME}/jbox.out
    }

jbox_restart () {
    jbox_stop
    jbox_start
    }

jbox_status () {
    PINFO="$(pgrep -u $(id -u) -a -f [a]lien.JBox)"
    [[ -z "${PINFO}" ]] && return 1;
    PID="${PINFO%% *}"
    LSOF="$(lsof -nPE -p ${PID})"
    echo "${LSOF}" | head -1
    CONNECTIONS=$(echo "${LSOF}" | grep -e 'ESTABLISHED)$\|LISTEN)$' ) #'
    [[ -n "${CONNECTIONS}" ]] && echo "${CONNECTIONS}" || echo "No connections so far for pid ${PID}.. wait a little bit more"

    JCLIENT_TOKEN="${TMPDIR}/jclient_token_$(id -u)"
    [[ -f "${JCLIENT_TOKEN}" ]] && echo -e "\njclient_token_ info\n$(< ${JCLIENT_TOKEN})" || echo "Connection not estblished yet and not reported in ${JCLIENT_TOKEN}.. wait a little bit more"
    }

if [ "${ARG1}" == "setup" ]; then
    #Copy the default logging and config files to user controllable versions - if present, keep the existing and copy the new ones with date postfix

    cat << EOF > ${JALIEN_CONF_DIR}/config.properties
ldap_server = alice-ldap.cern.ch:8389
ldap_root = o=alice,dc=cern,dc=ch
verify_ldap = true
alien.users.basehomedir = /alice/cern.ch/user/
alice_close_site = CERN
apiService = alice-jcentral.cern.ch:8098
jalien.config.hasDBBackend = false
alien.shell.commands.access_log=access_log
lfn_crawler_dry_run = true
#service.jks.location =
#user.jks.location =

EOF

    cat << EOF > ${JALIEN_CONF_DIR}/logging.properties
handlers = alien.log.SevereFileHandler alien.log.WarningFileHandler alien.log.ConfigFileHandler alien.log.InfoFileHandler alien.log.FineFileHandler alien.log.FinerFileHandler alien.log.FinestFileHandler
#alien.site.CustomHandler

java.util.logging.SimpleFormatter.format = %1$tc %2$s %4$s: [ %5$s ] %6 %n %7 %n

alien.log.SevereFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.SevereFileHandler.limit = 1000000
alien.log.SevereFileHandler.count = 4
alien.log.SevereFileHandler.append = true
alien.log.SevereFileHandler.pattern = ${JUSRDIR}/alien-severe%g.log

alien.log.WarningFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.WarningFileHandler.limit = 1000000
alien.log.WarningFileHandler.count = 4
alien.log.WarningFileHandler.append = true
alien.log.WarningFileHandler.pattern = ${JUSRDIR}/alien-warning%g.log

alien.log.ConfigFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.ConfigFileHandler.limit = 1000000
alien.log.ConfigFileHandler.count = 4
alien.log.ConfigFileHandler.append = true
alien.log.ConfigFileHandler.pattern = ${JUSRDIR}/alien-config%g.log

alien.log.InfoFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.InfoFileHandler.limit = 1000000
alien.log.InfoFileHandler.count = 4
alien.log.InfoFileHandler.append = true
alien.log.InfoFileHandler.pattern = ${JUSRDIR}/alien-info%g.log

alien.log.FineFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.FineFileHandler.limit = 1000000
alien.log.FineFileHandler.count = 4
alien.log.FineFileHandler.append = true
alien.log.FineFileHandler.pattern = ${JUSRDIR}/alien-fine%g.log

alien.log.FinerFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.FinerFileHandler.limit = 1000000
alien.log.FinerFileHandler.count = 4
alien.log.FinerFileHandler.append = true
alien.log.FinerFileHandler.pattern = ${JUSRDIR}/alien-finer%g.log

alien.log.FinestFileHandler.formatter = java.util.logging.SimpleFormatter
alien.log.FinestFileHandler.limit = 1000000
alien.log.FinestFileHandler.count = 4
alien.log.FinestFileHandler.append = true
alien.log.FinestFileHandler.pattern = ${JUSRDIR}/alien-finest%g.log

.level = WARNING
lia.level = WARNING
lazyj.level = WARNING
apmon.level = WARNING
apmon.MonitoredJob.level=OFF
alien.level = FINEST
alien.monitoring.Monitor.level = WARNING
alien.site.JobAgent.level = FINE

# tell LazyJ to use the same logging facilities
use_java_logger=true

EOF

    #mkdir -p ${HOME}/.j/trusts
    #wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Certification%20Authority.crt" -O ${HOME}/.j/trusts/CERN_CA.der
    #wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Root%20Certification%20Authority%202.crt" -O ${HOME}/.j/trusts/CERN_ROOT_CA2.der
    #wget -q "https://cafiles.cern.ch/cafiles/certificates/CERN%20Grid%20Certification%20Authority.crt" -O ${HOME}/.j/trusts/CERN_Grid_CA.der
    exit 0 # we done our job, let's exit
elif [ "${ARG1}" == "cleanup" ]; then
    jbox_stop
    exit $? # we done our job, let's exit
elif [ "${ARG1}" == "login" ]; then
    jbox_start
    exit $?
elif [ "${ARG1}" == "login_restart" ]; then
    jbox_restart
    exit $?
elif [ "${ARG1}" == "jbox_status" ]; then
    jbox_status
    exit $?
else
    RUNSH_OPTS="${RUNSH_OPTS} alien.JSh"
fi

if [[ ! -f "${JALIEN_CONF_DIR}/config.properties" ]]; then # ups, setup was not run
    echo "could not find ${JALIEN_CONF_DIR}; you should run:"
    echo "${0} setup"
    exit 1
fi

if [[ -n ${ARGLIST} ]]; then
    JBOX_PID="$(pgrep -u $(id -u) -a -f [a]lien.JBox)"
    [[ -z "${JBOX_PID}" ]] && jbox_start
    java ${JALIEN_OPTS_DEFAULT} ${RUNSH_OPTS} <<< ${ARGLIST} | head -n -2 | tail -n +7
else
    java ${JALIEN_OPTS_DEFAULT} ${RUNSH_OPTS}
fi

