#!/bin/bash

ldap_umd_glue1 sbdii.spacescience.ro:2170 RO-13-ISS objectClass=GlueCE
echo
ldap_umd_glue2 sbdii.spacescience.ro:2170 RO-13-ISS '(&(objectClass=GLUE2Manager)(GLUE2ManagerProductName=slurm))'

