#!/usr/bin/bash

ldapsearch -o ldif-wrap=no -x -LLL -H ldap://lcg-bdii.egi.eu:2170 -b "GLUE2DomainID=RO-13-ISS,GLUE2GroupID=grid,o=glue" '(objectClass=GLUE2Endpoint)' GLUE2EndpointImplementationName GLUE2EndpointInterfaceName GLUE2EndpointImplementationVersion GLUE2EndpointURL

