#!/bin/bash

ldap_umd_glue1 grid04.spacescience.ro:2170 RO-13-ISS objectClass=GlueSE
echo
ldap_umd_glue2 grid04.spacescience.ro:2170 RO-13-ISS '(&(objectClass=GLUE2Manager)(GLUE2ManagerProductName=DPM))'

