#!/bin/bash

HOST=${1}
shift

SITE=${1}
shift

[[ ${0} == *_glue2 ]] && GLUE="GLUE2DomainID=${SITE},o=glue" || GLUE="Mds-Vo-Name=${SITE},o=grid"

ldapsearch -o ldif-wrap=no -x -LLL -H ldap://${HOST} -b ${GLUE} "${@}"

