#!/usr/bin/bash

ldapsearch -o ldif-wrap=no -x -LLL -H ldap://sbdii.spacescience.ro:2170 -b "GLUE2DomainID=RO-13-ISS,o=glue" '(objectClass=GLUE2Endpoint)' GLUE2EndpointImplementationName GLUE2EndpointInterfaceName GLUE2EndpointImplementationVersion GLUE2EndpointURL

