#!/usr/bin/env bash

[[ -z "${LD_LIBRARY_PATH}" ]] && { echo "LD_LIBRARY_PATH not set"; exit; }

for libpath in $(echo $LD_LIBRARY_PATH | xargs -d ":"); do
    find ${libpath} -name '*.rootmap'
done

