#!/bin/bash

MYIP=$(host -t TXT o-o.myaddr.l.google.com ns1.google.com | awk '/o-o.myaddr.l.google.com/ {gsub("\"","",$NF);print $NF;}') #'

[[ -z "${MYIP}" ]] && MYIP=$(host -t A myip.opendns.com resolver1.opendns.com | awk '/myip.opendns.com/ {print $NF;}') #'
[[ -z "${MYIP}" ]] && MYIP=$(curl -s checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//') #'

echo "${MYIP}"

