#!/bin/sh
# Derived from pdf2ps.
# $Id: pdf2tif,v 1.0 2006/11/03 Fred Smith
# Convert PDF to TIFF file.

OPTIONS=""
while true
do
case "$1" in
-?*) OPTIONS="$OPTIONS $1" ;;
*) break ;;
esac
shift
done

if [ $# -eq 2 ]
then

    outfile=$2

elif [ $# -eq 1 ]
then

    outfile=`basename "$1" .pdf`-%02d.tif 

else

    echo "Usage: `basename $0` [-dASCII85EncodePages=false]

[-dLanguageLevel=1|2|3] input.pdf [output.ps]" 1>&2

    exit 1

fi

# Doing an initial 'save' helps keep fonts from being flushed between pages.
# We have to include the options twice because -I only takes effect if it
# appears before other options.
exec gs $OPTIONS -q -dNOPAUSE -dBATCH -dSAFER -r300x300 -sDEVICE=tiffg3 "-sOutputFile=$outfile" $OPTIONS -c save pop -f "$1"

