#!/bin/bash
echo "curent cpuinfo_cur_freq =" `cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
echo "curent scaling_cur_freq =" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` 
echo "curent guvernor =" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
echo powersave > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "curent guvernor =" `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`


