#!/bin/bash

SSH_REMOTE="${1}"
shift
LOCAL_PORT="${1}"
shift

# -D [bind_address:]port
# Specifies a local “dynamic” application-level port forwarding.  This works by allocating a socket to listen to port on the  local  side,
# optionally bound to the specified bind_address.

# -q      Quiet mode.
# -T      Disable pseudo-terminal allocation.
# -N      Do  not  execute  a remote command.  This is useful for just forwarding ports.
# -n      Redirects stdin from /dev/null (actually, prevents reading from stdin).  This must be used when ssh is run in the background.
# -f      Requests ssh to go to background just before command execution.
#         This is useful if ssh is going to ask for passwords or passphrases, but the user wants it in the background.  This implies -n.

## N.B. !!! The rest of default options for ssh are set in .ssh/conf.d/default !!!

/usr/bin/ssh -o "IPQoS=throughput" -C -TnNf ${@} -D "${LOCAL_PORT}" ${SSH_REMOTE}

