#!/bin/bash

echo "Updating ROOT head"
cd $tools/root/trunk-src
git pull

last_v5_tag=`git tag -l "v5-34-*" | tail -n 1`
last_v6_tag=`git tag -l "v6-*" | tail -n 1`

cd $ROOTSYS/..

rm -rf $ROOTSYS/../v5-34-src/*
rm -rf $ROOTSYS/../v5-34-src/.*

rm -rf $ROOTSYS/../v6-00-src/*
rm -rf $ROOTSYS/../v6-00-src/.*

git clone -l trunk-src v5-34-src
git clone -l trunk-src v6-00-src

cd $ROOTSYS/../v5-34-src
git checkout $last_v5_tag

cd $ROOTSYS/../v6-00-src/*
git checkout $last_v6_tag

