#!/usr/bin/env bash

FILE="/tmp/iss_issues.txt"
[[ -e "${FILE}" ]] && exit 1

source ${HOME}/.mail_issues_secrets

/home/adrian/bin/alimon_iss_issues > ${FILE}
echo >> ${FILE}
/usr/bin/ssh eos_mgm eos -b fs ls >> ${FILE}
echo >> ${FILE}
xrdmapc --list s -r rd.spacescience.ro:1094 | sort >> ${FILE}

/usr/bin/curl --url 'smtp://mail2.spacescience.ro:587' \
--ssl-reqd \
--mail-from 'adrian.sevcenco@spacescience.ro' \
--mail-rcpt 'glite@spacescience.ro' \
--upload-file ${FILE}  \
--user "${USER}:${PASS}" \
--login-options AUTH=PLAIN

/usr/bin/rm -f ${FILE}

