#!/usr/bin/env bash

LOCK="/tmp/iss_issues.lock"
[[ -e "${LOCK}" ]] && exit 1
touch "${LOCK}"
[[ -d "/var/www/html/issdc" ]] || { echo "Could not find /var/www/html/issdc dir"; exit 1; }
FILE="/var/www/html/issdc/iss_issues.txt"

source ${HOME}/.mail_issues_secrets

/home/adrian/bin/alimon_iss_issues > ${FILE} || { echo "Could not write into /var/www/html/issdc dir"; exit 1; }
echo >> ${FILE}
/usr/bin/ssh eos_mgm "/root/bin/eos_space_ls;echo;/root/bin/eos_fs_ls;" >> ${FILE}
echo >> ${FILE}
$HOME/bin/xrd_storage_info &>> ${FILE}
echo >> ${FILE}
$HOME/bin/storage_md_status &>> ${FILE}
echo >> ${FILE}
$HOME/bin/storage_smart_status &>> ${FILE}

/usr/bin/curl --url 'smtp://mail2.spacescience.ro:587' \
--ssl-reqd \
--mail-from 'adrian.sevcenco@spacescience.ro' \
--mail-rcpt 'glite@spacescience.ro' \
--upload-file ${FILE}  \
--user "${USER}:${PASS}" \
--login-options AUTH=PLAIN

sed -i '1,2d' ${FILE}

rm -rf "${LOCK}"

