#!/bin/bash

help () {
echo "
$0 NODE_NAME/RANGE STATE
1st arg is the None name and it is required;
Multiple node names may be specified using simple node range expressions (e.g. "lx[10-20]").

2nd arg is the state of the node with the following details:
"CANCEL_REBOOT", "DOWN", "DRAIN", "FAIL", "FUTURE", "RESUME", "NoResp", "POWER_DOWN", "POWER_UP" and "UNDRAIN".
If a node is in a "MIXED" state it usually means the node is in multiple states.

If a node is in a "MIXED" state it usually means the node is in multiple states.
For instance if only part of the node is "ALLOCATED" and the rest of the node is "IDLE" the state will be "MIXED".

"DOWN" will cause all running and suspended jobs on that node to be terminated.
"DRAIN" If you want to remove a node from service.
"FAILING" is similar to "DRAIN" except that some applications will seek to relinquish those nodes before the job completes.
"CANCEL_REBOOT" cancels a pending reboot on the node (same as "scontrol cancel_reboot <node>").
"RESUME" is not an actual node state, but will change a node state from "DRAINED", "DRAINING", "DOWN" or "REBOOT" to either "IDLE" or "ALLOCATED" state as appropriate.
"RESUME" will also clear the "POWERING_DOWN" state of a node and make it eligible to be allocted.
"UNDRAIN" clears the node from being drained (like "RESUME"), but will not change the node's base state (e.g. "DOWN").
"POWER_DOWN" and "POWER_UP" will use the configured SuspendProg and ResumeProg programs to explicitly place a node in or out of a power saving mode.
"
}

NODE="${1}"
shift

STATE="${1}"
shift

CMD="scontrol update nodename ${NODE} State=${STATE}"
exec ${CMD}

