#!/bin/bash

eval $(< $TMPDIR/jclient_token_$(id -u));

#CA="-CAfile ${HOME}/.globus/AliEn-CA.pem"
CA="-CAfile ${HOME}/.globus/AliEn-CA-NEW.pem"

#if [[ -z "${X509_CERT_DIR}" ]]; then
#    if [[ -e cvmfs/alice.cern.ch/etc/grid-security/certificates ]]; then
#        CA="-CApath /cvmfs/alice.cern.ch/etc/grid-security/certificates"
#    else
#        CA="-CApath /etc/grid-security/certificates"
#    fi
#fi

openssl s_client ${CA} -cert ${TMPDIR}/tokencert_1000.pem -key ${TMPDIR}/tokenkey_1000.pem "${@}" -connect ${JALIEN_HOST}:${JALIEN_WSPORT}

