#!/usr/bin/env bash

srv_list="mgm1 mgm2 mgm3 fst01 fst02 fst03 fst04 fst05 fst06 fst07 fst08 fst09 fst10 fst11 fst12 fst13 fst14 fst15"

for srv in ${srv_list}; do
    ${HOME}/bin/ssh_run_script ${srv} ${HOME}/bin/smart_health
    echo
done
