#!/usr/bin/env bash

srv_list="mgm1 mgm2 mgm3 fst01 fst02 fst03 fst04 fst05 fst06 fst07 fst08 fst09 fst10 fst11 fst12 fst13 fst14 fst16 fst17 fst18 fst19 fst20"

echo "   STORAGE SMART STATUS

"

for srv in ${srv_list}; do
    ssh ${srv} "/root/bin/smart_health; cat /run/smart_health.txt;"
    echo
done
