#!/bin/bash

srv_list="mgm1 mgm2 mgm3 fst01 fst02 fst03 fst04 fst05 fst06 fst07 fst08 fst09 fst10 fst11 fst12 fst13 fst14 fst15 fst16"

for srv in ${srv_list}; do
    ssh ${srv} 'echo -e "\n#########\n   $(hostname)\n#########";df -lh -x tmpfs -x devtmpfs --output=source,target,ipcent,size,pcent ; echo -e "\nMD STATUS" ;/root/bin/md_health report;'
done
