#!/bin/bash

v5="geant3-r5"
v6="geant3-r6"

cd $tools/alice

if [[ "$1" = "r5" ]] ; then
  switch_root r5
  unlink geant3
  ln -s ${v5} geant3
elif [[ "$1" = "r6" ]] ; then
  switch_root r6
  unlink geant3
  ln -s ${v6} geant3
else
  echo "options are : r5, r6"
fi

