#!/bin/bash

ALIPHYS_R5="physics-r5"
ALIPHYS_R6="physics-r6"

cd ${ALICE}

if [[ "$1" = "r6" ]] ; then
  switch_aliroot r6

  unlink aliphysics
  ln -s ${ALIPHYS_R6} aliphysics

elif [[ "$1" = "r5" ]] ; then
  switch_aliroot r5

  unlink aliphysics
  ln -s ${ALIPHYS_R5} aliphysics

else
  echo "arguments are r5, r6"
fi


