#!/bin/bash

ALIROOT_R5="v5-AN-r5"
ALIROOT_R6="v5-AN-r6"

cd ${ALICE}

if [[ "$1" = "r6" ]] ; then
  switch_root r6
  switch_geant3 r6

  unlink aliroot
  ln -s ${ALIROOT_R6} aliroot

elif [[ "$1" = "r5" ]] ; then
  switch_root r5
  switch_geant3 r5

  unlink aliroot
  ln -s ${ALIROOT_R5} aliroot

else
  echo "arguments are r5, r6"
fi


