#!/bin/bash

[[ -e ~/location ]] && location=`cat ~/location` || exit

[[ "$location" != "acasa" && "$location" != "t420" ]] && exit

##echo ${location}

RSYNC="rsync -aqhuHAXWz --delete"

ALIROOT_TRUNK="/home.hdd/physics-tools/alice/trunk-src/"
ALIROOTSRC="/home.hdd/physics-tools/alice/v5-AN-latest-src/"
ALIPHYSSRC="/home.hdd/physics-tools/alice/physics-src/"
GEANT3SRC="/home.hdd/physics-tools/alice/geant3-src/"

ALIROOT_R5="/home.hdd/physics-tools/alice/v5-AN-r5/"
ALIROOT_R6="/home.hdd/physics-tools/alice/v5-AN-r6/"

ALIPHYS_R5="/home.hdd/physics-tools/alice/physics-r5/"
ALIPHYS_R6="/home.hdd/physics-tools/alice/physics-r6/"

GEANT3_R5="/home.hdd/physics-tools/alice/geant3-r5/"
GEANT3_R6="/home.hdd/physics-tools/alice/geant3-r6/"

mkdir -p ${ALIROOT_TRUNK} ${ALIROOTSRC} ${ALIPHYSSRC} ${GEANT3SRC} ${ALIROOT_R5} ${ALIROOT_R6} ${ALIPHYS_R5} ${ALIPHYS_R6} ${GEANT3_R5} ${GEANT3_R6}

${RSYNC} --compress-level=9 iss:${ALIROOT_TRUNK} ${ALIROOT_TRUNK}
${RSYNC} --compress-level=9 iss:${ALIROOTSRC}    ${ALIROOTSRC}
${RSYNC} --compress-level=9 iss:${ALIPHYSSRC}    ${ALIPHYSSRC}
${RSYNC} --compress-level=9 iss:${GEANT3SRC}     ${GEANT3SRC}

${RSYNC} iss:${ALIROOT_R5}       ${ALIROOT_R5}
${RSYNC} iss:${ALIROOT_R6}       ${ALIROOT_R6}

${RSYNC} iss:${ALIPHYS_R5}       ${ALIPHYS_R5}
${RSYNC} iss:${ALIPHYS_R6}       ${ALIPHYS_R6}

${RSYNC} iss:${GEANT3_R5}        ${GEANT3_R5}
${RSYNC} iss:${GEANT3_R6}        ${GEANT3_R6}




