#!/bin/bash

[[ -e ~/location ]] && location=`cat ~/location` || exit

[[ "$location" != "acasa" && "$location" != "t420" ]] && exit

##echo ${location}

RSYNC="rsync -aqhuHAXWz --delete"

ALIROOT_TRUNK="/home.hdd/physics-tools/alice/trunk-src/"
ALIROOTSRC="/home.hdd/physics-tools/alice/v5-AN-latest-src/"
ALIPHYSSRC="/home.hdd/physics-tools/alice/physics-src/"
GEANT3SRC="/home.hdd/physics-tools/alice/geant3-src/"


ALIROOT-R5="/home.hdd/physics-tools/alice/v5-AN-r5/"
ALIROOT-R6="/home.hdd/physics-tools/alice/v5-AN-r6/"

ALIPHYS-R5="/home.hdd/physics-tools/alice/physics-r5/"
ALIPHYS-R6="/home.hdd/physics-tools/alice/physics-r6/"

GEANT3-R5="/home.hdd/physics-tools/alice/geant3-r5/"
GEANT3-R6="/home.hdd/physics-tools/alice/geant3-r6/"

mkdir -p ${ALIROOT_TRUNK} ${ALIROOTSRC} ${ALIPHYSSRC} ${GEANT3src} ${ALIROOT-R5} ${ALIROOT-R6} ${ALIPHYS-R5} ${ALIPHYS-R6} ${GEANT3-R5} ${GEANT3-R6}

${RSYNC} --compress-level=9 iss:${ALIROOT_TRUNK} ${ALIROOT_TRUNK}
${RSYNC} --compress-level=9 iss:${ALIROOTSRC}    ${ALIROOTSRC}
${RSYNC} --compress-level=9 iss:${ALIPHYSSRC}    ${ALIPHYSSRC}
${RSYNC} --compress-level=9 iss:${GEANT3SRC}     ${GEANT3SRC}

${RSYNC} iss:${ALIROOT-R5}       ${ALIROOT-R5}
${RSYNC} iss:${ALIROOT-R6}       ${ALIROOT-R6}

${RSYNC} iss:${ALIPHYS-R5}       ${ALIPHYS-R5}
${RSYNC} iss:${ALIPHYS-R6}       ${ALIPHYS-R6}

${RSYNC} iss:${GEANT3-R5}        ${GEANT3-R5}
${RSYNC} iss:${GEANT3-R6}        ${GEANT3-R6}




