#!/usr/bin/env bash

DEF_BRANCH=$(git_default_branch)
git checkout ${DEF_BRANCH}
git fetch -t --all
git pull --rebase
git fetch -t upstream
git pull --rebase upstream ${DEF_BRANCH}
echo "now push to origin (git push --all) and then start development"

