#!/bin/bash

[[ -z "$1" ]] && { echo "Usage : $0 DEV PEER_IP_CIDR PRIV_KEY_CLIENT_FILE SERVER:PORT SERVER_PUB_KEY_STR" && exit; }

PORT=43333

DEV="${1}"
IP_CIDR="${2}"
PRIV_KEY="${3}"
SERVER_PORT="${4}"
SERVER_PUB_KEY="${5}"

WG_IFACES=$(ip -o -d link show | awk -F": " '/wireguard/ {print $2}')

## if already setup
if [[ "${DEV}" =~ "${WG_IFACES}" ]] ; then
    echo "Interface ${DEV} already created"
    echo "to remove it use :"
    echo "ip link del dev ${DEV} 2>/dev/null"
    exit
fi

ip link    add dev ${DEV} type wireguard mtu 9000 txqueuelen 20000
ip address add dev ${DEV} ${IP_CIDR}

wg set ${DEV} private-key ${PRIV_KEY} peer "${SERVER_PUB_KEY}" allowed-ips 0.0.0.0/0 endpoint "${SERVER_PORT}" persistent-keepalive 25

ip link set up dev ${DEV}

wg showconf ${DEV} > ${DEV}_client.conf

