#!/bin/bash

[[ -z "$1" ]] && { echo "Usage : $0 DEV IP_CIDR PRIV_KEY_FILE" && exit; }

PORT=43333

DEV="${1}"
IP_CIDR="${2}"
PRIV_KEY="${3}"

WG_IFACES=$(ip -o -d link show | awk -F": " '/wireguard/ {print $2}')

## if already setup
if [[ "${WG_IFACES}" =~ "${DEV}" ]] ; then
    echo "Interface ${DEV} already created"
    echo "to remove it use :"
    echo "ip link del dev ${DEV} 2>/dev/null"
    exit
fi

ip link add dev ${DEV} mtu 9000 txqueuelen 20000 type wireguard
ip addr add dev ${DEV} ${IP_CIDR}

wg set ${DEV} private-key ${PRIV_KEY} listen-port ${PORT}

ip link set up dev ${DEV}

wg showconf ${DEV} > ${DEV}_server_$(date +%Y%m%d_%H%M%S).conf

