#!/bin/bash

sudo -s -- <<EOF
/home/adrian/bin/wg_service /etc/wireguard/server.conf stop
/home/adrian/bin/wg_service /etc/wireguard/server.conf show
/home/adrian/bin/wg_service /etc/wireguard/server.conf show

/home/adrian/bin/wg_service /etc/wireguard/server443.conf stop
/home/adrian/bin/wg_service /etc/wireguard/server443.conf show
/home/adrian/bin/wg_service /etc/wireguard/server443.conf show

EOF

