#!/bin/bash

ARG="${1}"

if [[ "${ARG}" == "list" || -z "${ARG}" ]]; then
    sudo -s -- <<EOF
ls -la /etc/wireguard/*.conf
EOF
else
    sudo -s -- <<EOF
/home/adrian/bin/wg_service /etc/wireguard/${ARG}.conf stop
sleep 1
/home/adrian/bin/wg_service /etc/wireguard/${ARG}.conf show
/home/adrian/bin/wg_service /etc/wireguard/${ARG}.conf show
EOF

fi

## no idea why it need 2 show commands to work

