#!/bin/bash

[[ -z "$1" ]] && { echo "Usage : $0 DEV PEER_PUB_KEY PEER_IP_CIDR" && exit; }

DEV=$1
PEER_PUB_KEY=$2
PEER_IP_CIDR=$3

WG_IFACES=$(ip -o -d link show | awk -F": " '/wireguard/ {print $2}')

if [[ ! "${WG_IFACES}" =~ "${DEV}" ]] ; then
    echo "Interface ${DEV} not found"
    echo "use wg_init_server or set up manually to add peers"
    exit
fi

wg set ${DEV} peer ${PEER_PUB_KEY} allowed-ips ${PEER_IP_CIDR}
wg showconf ${DEV} > ${DEV}_server.conf

