#!/bin/bash

PFN="${1}"

get_locations () {
echo -n "${1}" | python3 -c '
import os,sys
from urllib.parse import urlparse
pfn = sys.stdin.read();
url = urlparse(pfn)
print(f"srv={url.netloc}")
print(f"path={url.path}")
'
}

[[ -n "${2}" ]] && FLAG_QUERY=" -q ${2}"
eval $(get_locations "${PFN}")

if [[ -n "${FLAG_QUERY}" ]]; then
    xrdfs "${srv}" stat ${FLAG_QUERY} "${path}" &>/dev/null && echo "OK" || echo "FAIL"
else
    echo -e "Server:\t${srv}"
    xrdfs "${srv}" stat "${path}"
fi

