#!/bin/bash

redir=$1

#xrdinfo=`echo -ne "query config version\nspaceinfo /\nexit\n" |/usr/bin/xrdfs rd.spacescience.ro:1094`

xrdinfo=$(echo -ne "query stats i\nspaceinfo /\nexit\n" | xrdfs ${redir}:1094)
# get xrd space info; Reported size in bytes; convert to GiB with 2 decimals
totsp=$(echo "$xrdinfo" | grep Total | awk -F: '{printf "%.2f\n",$2/1073741824}')
freesp=$(echo "$xrdinfo" | grep Free | awk -F: '{printf "%.2f\n",$2/1073741824}')

stats=$(echo "$xrdinfo" | grep statistics | awk -F'[<>]' '{print $2}')
arrstats=($stats)
eval ${arrstats[2]}
eval ${arrstats[8]}

echo "Xrootd cluster name is : $site and is running xrootd version $ver"
echo "Total space in xrootd cluster : ${redir}"
echo -e "Total space (GiB) :\t${totsp}"
echo -e "Free space (GiB) :\t${freesp}"
echo

for srv in $(xrdmapc --list s -r ${redir}:1094 | awk '/Srv/ {print $2}'); do
  xrdinfo=$(echo -ne "spaceinfo /\nexit\n" | xrdfs $srv)

  # get xrd space info; Reported size in bytes; convert to GiB with 2 decimals
  totsp=$(echo "$xrdinfo" | grep Total | awk -F: '{printf "%.2f\n",$2/1073741824}')
  freesp=$(echo "$xrdinfo" | grep Free | awk -F: '{printf "%.2f\n",$2/1073741824}')

  echo "xrootd storage server : ${srv}"
  echo -e "Total space (GiB) :\t${totsp}"
  echo -e "Free space (GiB) :\t${freesp}"
  echo
done

