#!/usr/bin/env bash

CWD="$(pwd -P)"
BNAME="$(basename ${CWD})"

cleanup () {
rm -rf publish.sh;
}

rm -rf ~/.local/lib/python*/site-packages/{XRootD,pyxrootd,xrootd*}

python3 -m pip --quiet install --upgrade build
command cp -f -r packaging/wheel/* .
find dist -type f -name "xrootd-*" -exec rm -rf {} \;
./publish.sh

cd ..
python3 -m pip install --user --upgrade ${BNAME}/dist/xrootd-*.tar.gz

cd "${CWD}"
cleanup
git reset --hard
