#!/usr/bin/env bash

CWD="$(pwd -P)"
BNAME="$(basename ${CWD})"

cleanup () {
rm -rf MANIFEST.in install.sh publish.sh setup.py TestCXX14.txt bindings/python/setup.py has_c++14.sh bindings/python/VERSION dist xrootd.egg-info packaging/wheel/xrootd.egg-info;
}

rm -rf ~/.local/lib/python*/site-packages/{XRootD,pyxrootd,xrootd*}
cleanup

python3 -m pip --quiet install --upgrade build
command cp -f -r packaging/wheel/* .
find dist -type f -name "xrootd-*" -exec rm -rf {} \;
./publish.sh

cd ..
python3 -m pip install --user --upgrade ${BNAME}/dist/xrootd-*.tar.gz

cd "${CWD}"
cleanup

