#!/bin/bash

RSAR_DIR="${HOME}/GIT-REPOS/rsar"
pushd ${RSAR_DIR}
git checkout master && git pull
sudo cp -f ${RSAR_DIR}/rsar /usr/local/bin/ 
sudo cp -f ${RSAR_DIR}/rsar-bash-completion.bash /etc/bash_completion.d/
cp -f ${RSAR_DIR}/rsar ~/bin/ ; cp -f ${RSAR_DIR}/rsar-bash-completion.bash ~/bin/env/
popd

XSOS_DIR="${HOME}/GIT-REPOS/xsos"
pushd ${XSOS_DIR}
git checkout master && git pull
sudo cp -f ${XSOS_DIR}/xsos /usr/local/bin/
sudo cp -f ${XSOS_DIR}/xsos-bash-completion.bash /etc/bash_completion.d/
cp -f ${XSOS_DIR}/xsos ~/bin/ ; cp -f ${XSOS_DIR}/xsos-bash-completion.bash ~/bin/env/
popd

