#!/bin/bash

[[ -z "${1}" ]] && echo "no argumet; it should be the mounted partition" && exit

DIR="/${1}/fio"
mkdir -p ${DIR}
OUTPUT="${0}.txt"


fio --directory=${DIR} --rw="read" --refill_buffers --fallocate=none --norandommap --randrepeat=0 --ioengine=libaio \
--direct=1 --bs=1m --size=4g --iodepth=1 --numjobs=1 --runtime=300 \
--group_reporting --name="test" --output=${OUTPUT} --output-format=normal

