#!/bin/bash
#####################
###   FUNCTIONS   ###
#####################

functions_list () { declare -f; }
functions_list_name () { declare -F; }
functions_show_def () { declare -f $1; }

SourceIfValid () { [[ -f $1 ]] && source $1; }

__PATH_INS () { [[ "$PATH" =~ "$1" ]] && return 0; [[ -z $PATH ]] && export PATH=$1 || export PATH=$1:$PATH; }
__PATH_ADD () { [[ "$PATH" =~ "$1" ]] && return 0; [[ -z $PATH ]] && export PATH=$1 || export PATH=$PATH:$1; }

__LDLIB_INS () { [[ "$LD_LIBRARY_PATH" =~ "$1" ]] && return 0; [[ -z $LD_LIBRARY_PATH ]] && export LD_LIBRARY_PATH=$1 || export LD_LIBRARY_PATH=$1:$LD_LIBRARY_PATH ; }
__LDLIB_ADD () { [[ "$LD_LIBRARY_PATH" =~ "$1" ]] && return 0; [[ -z $LD_LIBRARY_PATH ]] && export LD_LIBRARY_PATH=$1 || export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$1 ; }

__PYPATH_INS () { [[ "$PYTHONPATH" =~ "$1" ]] && return 0; [[ -z $PYTHONPATH ]] && export PYTHONPATH=$1 || export PYTHONPATH=$1:$PYTHONPATH; }
__PYPATH_ADD () { [[ "$PYTHONPATH" =~ "$1" ]] && return 0; [[ -z $PYTHONPATH ]] && export PYTHONPATH=$1 || export PYTHONPATH=$PYTHONPATH:$1; }

__MANPATH_INS () { [[ "$MANPATH" =~ "$1" ]] && return 0; [[ -z $MANPATH ]] && export MANPATH=$1 || export MANPATH=$1:$MANPATH; }
__MANPATH_ADD () { [[ "$MANPATH" =~ "$1" ]] && return 0; [[ -z $MANPATH ]] && export MANPATH=$1 || export MANPATH=$MANPATH:$1; }

cvmfs_alice_load ()      { eval $(alienv printenv VO_ALICE@$1); }
cvmfs_alicephys_load ()  { eval $(alienv printenv VO_ALICE@AliPhysics::$1); }
cvmfs_alice_enter ()     { alienv enter VO_ALICE@$1; }
cvmfs_alicephys_enter () { alienv enter VO_ALICE@AliPhysics::$1; }

cvmfs_alicephys_load_latest () {
local latest=$(alienv -t avail AliPhysics 2>&1 | awk -F"/" '/vAN-/ {print $2}' | tail -n 1)
eval $(alienv printenv VO_ALICE@AliPhysics::$latest)
}

cvmfs_alicephys_enter_latest () {
local latest=$(alienv -t avail AliPhysics 2>&1 | awk -F"/" '/vAN-/ {print $2}' | tail -n 1)
alienv enter VO_ALICE@AliPhysics::$latest
}

__cvmfs_enabled () { [[ "${ALICE_ENV}" == "1" ]] && echo "#CVMFS"; }

__cvmfs_get_aliphys () { /cvmfs/alice.cern.ch/bin/alienv -t list 2>&1 | awk -F"/" '/AliPhysics/ {print ":"$2"#"}'; }

alibuild_list_inits  () { ls -1 --hide=sw ${ALICE_WORK_DIR}/.. ;}
alibuild_list_builds () { /usr/bin/find ${ALICE_WORK_DIR}/${ALIBUILD_ARCH}/AliPhysics -mindepth 1 -maxdepth 1 -type d -printf "%f\n"; }
alibuild_list_links  () { /usr/bin/find ${ALICE_WORK_DIR}/${ALIBUILD_ARCH}/AliPhysics -mindepth 1 -maxdepth 1 -type l -printf "%f -> %l\n"; }
alibuild_list_labels () { /usr/bin/find ${ALICE_WORK_DIR}/${ALIBUILD_ARCH}/AliPhysics -mindepth 1 -maxdepth 1 -printf "%f\n";}
alibuild_init        () { aliBuild init AliRoot,AliPhysics -z; }

qstat_slr_f () { scontrol show jobid -dd $1; }

slr_job_r_stat () { sstat --format=AveCPU,AvePages,AveRSS,AveVMSize,JobID -j $1 --allsteps; }

slr_job_c_stat () { sacct -j $1 --format=JobID,JobName,MaxRSS,Elapsed; }

slr_joball_c_stat () { sacct -u $(id -un) --format=JobID,JobName,MaxRSS,Elapsed; }

###########################################################
##   GIT
git_push2master_current () {
local branch_name=$(git symbolic-ref --short -q HEAD)
git push origin $branch_name:master
}

git_push2master_byname () {
[[ -z $1 ]] && echo "An argument is needed : the branch name" && return

local branch_list=$(git branch -l)
[[ !( "$branch_list" =~ "$1" ) ]] && echo "The argument need to be a valid branch name" && return

git push origin $1:master
}

git_branch_name () { git symbolic-ref --short -q HEAD; }

git_l () {
git log --graph --pretty=format:'%C(yellow)%h%C(cyan)%d%Creset %s %C(white)- %an, %ar%Creset'
}

git_list () {
git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short
}

git_whatis () {
git show -s --pretty='tformat:%h (%s, %ad)' --date=short
}

git_pwhatis () {
git show -s --pretty='tformat:%h, %s, %ad' --date=short
}

git_update () { git fetch -t --all && git pull --rebase; }

git_rebase_local () {
local branch_name=$(git symbolic-ref --short -q HEAD)
git checkout master
git fetch -t --all
git pull --rebase
git checkout ${branch_name}
git pull --rebase . master
}

git_delete_branch () {
git checkout master
git fetch -p origin
git push origin --delete $1
git branch -D $1
git remote prune origin
git fetch -p origin
}

###########################################################

now_str () { date +%Y%m%d_%H%M%S; }

pic_date () { exiftool $1 | grep "Date/Time Original"; }
pic_info () { identify -format "Size : %wx%h ; DPI : %xx%y\n" $1; }

proc_info () { ps -eo pid,%cpu,rss,args | grep -i $1 | grep -v grep; }

# Prints the time given in seconds in hours, minutes, seconds
NiceTime () {
  local SS HH MM STR
  SS="$1"

  let "HH=SS / 3600"
  let "SS=SS % 3600"
  [ $HH -gt 0 ] && STR=" ${HH}h"

  let "MM=SS / 60"
  let "SS=SS % 60"
  [ $MM -gt 0 ] && STR="${STR} ${MM}m"

  [ $SS -gt 0 ] && STR="${STR} ${SS}s"
  [ "$STR" == "" ] && STR="0s"

  echo $STR

  #printf "%02dh %02dm %02ds" $HH $MM $SS
}

whereami () {
local host=$(hostname -s)
local fullhost=$(hostname -f)
[[ "$fullhost" = "sev.spacescience.ro" ]] && host="ISS"
echo $host
}


cxxflags () {
CXXFLAGS='-march=native -O2'

local avx_enable=$(grep avx /proc/cpuinfo &> /dev/null && echo yes)
[[ ${avx_enable} == "yes" ]] && CXXFLAGS="${CXXFLAGS} -mavx"

export CXXFLAGS
export CFLAGS=${CXXFLAGS}
}

mymake () {
local CPUS=$(grep processor /proc/cpuinfo | wc -l)
nohup time -p make -k -j${CPUS} >$(basename $PWD).out 2>$(basename $PWD).err &
}

mymake_stop () {
local CPUS=$(grep processor /proc/cpuinfo | wc -l)
nohup time -p make --stop -j${CPUS} >$(basename $PWD).out 2>$(basename $PWD).err &
}

eth_irq () {
        if [ "$1" = "all" ]; then
            local list_of_eth=$(ip link | grep -E -o "eth[0-99]");
            for eth in $list_of_eth; do
               grep --color $eth /proc/interrupts | cut -d \: -f 1 | awk '{print $1}'
            done;
        elif [ -n "$1" ]; then
            grep --color $1 /proc/interrupts | cut -d \: -f 1 | awk '{print $1}';
        else
            echo "Accepted arguments are : ";
            echo " all     : print IRQ's for all eth's";
            echo " ethX    : print IRQ for ethX";
        fi
}

ex () {
    if [ -f $1 ]; then
        case $1 in
            *.tar.bz2)
                tar xjf $1
            ;;
            *.tar.gz)
                tar xzf $1
            ;;
            *.bz2)
                bunzip2 $1
            ;;
            *.rar)
                unrar x $1
            ;;
            *.gz)
                gunzip $1
            ;;
            *.tar)
                tar xf $1
            ;;
            *.tbz2)
                tar xjf $1
            ;;
            *.tgz)
                tar xzf $1
            ;;
            *.zip)
                unzip $1
            ;;
            *.Z)
                uncompress $1
            ;;
            *.7z)
                7z x $1
            ;;
            *)
                echo "'$1' cannot be extracted via extract()"
            ;;
        esac;
    else
        echo "'$1' is not a valid file";
    fi
}


files2Lower () {
    for file in *; do
        lc=$(echo "$file" | tr "[A-Z]" "[a-z]");
        [[ $lc != $file ]] && mv -i "$file" "$lc";
    done
}

mkcd () { mkdir $1 && cd $1; }

quote () { echo \'${1//\'/\'\\\'\'}\'; }

toLower () { echo $1 | tr "[:upper:]" "[:lower:]"; }
toUpper () { echo $1 | tr "[:lower:]" "[:upper:]"; }

tarxz () {
XZ_OPT="--check=sha256 -T0" tar cJ --acls --xattrs --selinux -f ${1}.tar.xz ${1}
}

diff_short ()    { diff --suppress-common-lines $1 $2; }
diff_u_short ()  { diff -u --suppress-common-lines $1 $2; }
diff_wu_short () { diff -wu --suppress-common-lines $1 $2; }

diff_long ()    { diff $1 $2; }
diff_u_long ()  { diff -u $1 $2; }
diff_wu_long () { diff -wu $1 $2; }

diff_code   () { diff  -u "$@" <(grep -vE '^\s*(#|$|//)' $1)  <(grep -vE '^\s*(#|$|//)' $2); }
diff_code_w () { diff -wu "$@" <(grep -vE '^\s*(#|$|//)' $1)  <(grep -vE '^\s*(#|$|//)' $2); }

root-module () {
  if [ $# -lt 1 ] ; then
    echo "root-module need exactly one argument"
    return 1
  fi

  local name=$(basename $1 .cxx)
  local root_cflags = $(root-config --cflags)

  g++ -fPIC -Wall -g -c $name.cxx -o $name.o ${root_cflags}
  rootcint -f ${name}Cint.cxx -c ${name}.h
  g++ -fPIC -Wall -g -c ${name}Cint.cxx -o ${name}Cint.o ${root_cflags}
  g++ -fPIC -shared -Wl,-soname,${name}.so -o ${name}.so ${name}Cint.o ${name}.o
  rm -f ${name}Cint.cxx ${name}Cint.h ${name}Cint.o ${name}.o
}


transfer () {
    # check arguments
    if [ $# -eq 0 ]; then
        echo "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"
        return 1
    fi

    curl --version 2>&1 > /dev/null
    if [ $? -ne 0 ]; then
      echo "Could not find curl."; return
    fi

    # get temporarily filename, output is written to this file show progress can be showed
    tmpfile=$( mktemp -t transferXXX )

    # upload stdin or file
    file=$1

    if tty -s; then
        basefile=$(basename "$file" | sed -e 's/[^a-zA-Z0-9._-]/-/g')

        if [ ! -e $file ]; then
            echo "File $file doesn't exists."
            return 1
        fi

        if [ -d $file ]; then
            # zip directory and transfer
            zipfile=$( mktemp -t transferXXX.zip )
            cd $(dirname $file) && zip -r -q - $(basename $file) >> $zipfile
            curl --progress-bar --upload-file "$zipfile" "https://transfer.sh/$basefile.zip" >> $tmpfile
            rm -f $zipfile
        else
            # transfer file
            curl --progress-bar --upload-file "$file" "https://transfer.sh/$basefile" >> $tmpfile
        fi
    else
        # transfer pipe
        curl --progress-bar --upload-file "-" "https://transfer.sh/$file" >> $tmpfile
    fi

    # cat output link
    cat $tmpfile

    # cleanup
    rm -f $tmpfile
}

job_start_local () { cd $1 && (nohup ./cmd &>cmd_output.txt &) && cd .. ; }

date_baby () {
    local d1=$(date -d "$1" +%s)
    local d2=$(date +%s)
    echo $(( (d2 - d1) / 86400 )) days
}

###################
###   OpenSSL   ###
###################

openssl_verify ()     { openssl verify -CApath $1 $2; }
openssl_check_csr ()  { openssl req -text -noout -verify -in $1; }
openssl_check_key ()  { openssl rsa -in $1 -check; }
openssl_check_cert () { openssl x509 -in $1 -text -noout; }
openssl_cert_txt ()   { openssl x509 -in $1 -text; }
openssl_check_p12 ()  { openssl pkcs12 -info -in $1; }
openssl_compare_key_cert () { diff -qs <(openssl rsa -in $1 -pubout) <(openssl x509 -in $2 -pubkey -noout); }

openssl_pem_p12 () {
local name=$(basename $1 .pem)
local txt=$3
openssl pkcs12 -export -in $1 -inkey $2 -out ${name}.p12 -name ${txt}
}

openssl_p12_pem () {
openssl pkcs12 -clcerts -nokeys -out usercert.pem -in $1
openssl pkcs12 -nocerts -out userkey.pem -in $1
}

openssl_DN () {
local filename=$(basename "$1")
local ext="${filename##*.}"
if [[ "$ext" == "pem" ]] ; then
    openssl x509 -in $1 -noout -subject | sed 's/subject= //';
elif [[ "$ext" == "p12" ]] ; then
    openssl pkcs12 -in $1 -nokeys -clcerts | openssl x509 -noout -subject | sed 's/subject= //';
fi
}

openssl_key_nopass () {
local priv1=$(basename "$1")
local ext="${priv1##*.}"
local filename="${priv1%.*}"
local priv2="${filename}_nopass.${ext}"
openssl rsa -in $1 -out ${priv2}
}

function __wget() {
    : ${DEBUG:=0}
    local URL=$1
    local tag="Connection: close"

    if [ -z "${URL}" ]; then
        printf "Usage: %s \"URL\" [e.g.: %s http://www.google.com/]" \
               "${FUNCNAME[0]}" "${FUNCNAME[0]}"
        return 1;
    fi
    read proto server path <<<$(echo ${URL//// })
    local SCHEME=${proto//:*}
    local PATH=/${path// //}
    local HOST=${server//:*}
    local PORT=${server//*:}

    [[ "$SCHEME" != "http" ]] && { printf "sorry, %s only support http\n" "${FUNCNAME[0]}"; return 1; }

    [[ x"${HOST}" == x"${PORT}" ]] && PORT=80
    [[ $DEBUG -eq 1 ]] && echo "SCHEME=$SCHEME" >&2
    [[ $DEBUG -eq 1 ]] && echo "HOST=$HOST" >&2
    [[ $DEBUG -eq 1 ]] && echo "PORT=$PORT" >&2
    [[ $DEBUG -eq 1 ]] && echo "PATH=$PATH" >&2

    exec 3<>/dev/tcp/${HOST}/$PORT
    [[ $? -ne 0 ]] && return $?

    echo -en "GET ${PATH} HTTP/1.1\r\nHost: ${HOST}\r\n${tag}\r\n\r\n" >&3
    [[ $? -ne 0 ]] && return $?

    # 0: at begin, before reading http response
    # 1: reading header
    # 2: reading body
    local state=0
    local num=0
    local code=0
    while read line; do
        num=$(($num + 1))
        # check http code
        if [ $state -eq 0 ]; then
            if [ $num -eq 1 ]; then
                if [[ $line =~ ^HTTP/1\.[01][[:space:]]([0-9]{3}).*$ ]]; then
                    code="${BASH_REMATCH[1]}"
                    if [[ "$code" != "200" ]]; then
                        printf "failed to wget '%s', code is not 200 (%s)\n" "$URL" "$code"
                        exec 3>&-
                        return 1
                    fi
                    state=1
                else
                    printf "invalid http response from '%s'" "$URL"
                    exec 3>&-
                    return 1
                fi
            fi
        elif [ $state -eq 1 ]; then
            if [[ "$line" == $'\r' ]]; then
                # found "\r\n"
                state=2
            fi
        elif [ $state -eq 2 ]; then
            # redirect body to stdout
            # TODO: any way to pipe data directly to stdout?
            echo "$line"
        fi
    done <&3
    exec 3>&-
}

